name: Build Artifacts (manual dispatch)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout GemstoneGG feature/folia
        uses: actions/checkout@v7
        with:
          repository: GemstoneGG/FastAsyncWorldEdit-Folia
          ref: feature/folia

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 25
          cache: gradle

      - name: Build
        run: ./gradlew build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: FastAsyncWorldEdit-Paper-jars
          path: worldedit-bukkit/build/libs/FastAsyncWorldEdit-Paper-*.jar
          retention-days: 7
